### ISSUE TITLE
Is this project forgotten?

### ISSUE THREAD

**Issue by felixekman** [respeaker/Alexa#12]
@xiongyihui @yexiaobo-seeedstudio Have you guys stoped this project and left us backers without releasing the promised version V2 that supports the new Alexa apis?

**Comment by sevencheng798** [comment]
@felixekman I found a good open source hardware that supports alexa - WisCore board, your can try to experience it as great as using Echo. to share a link: https://github.com/RAKWireless/WisCore/wiki/WisAvs

**Comment by felixekman** [comment]
@sevencheng798 Thanks, I've seen your project. But sadly the board in question and the firmware is not compatible with this project. Wrong version of MT7XXX we need it for MT7688. Also, there seems to be other things severely lacking from the platform. For all it's faults the Respeaker is a fine hardware platform, if the makers ( @xiongyihui ) can just get their act together and focus on finishing developing for the already released platform as promised originally.

**Comment by xiongyihui** [comment]
@felixekman Thanks for your feedback. The V2 should be higher priority. Sorry for that.

@sevencheng798 It seems you only provide binary version alexa app.

**Comment by jdschuitemaker** [comment]
Any update on this @xiongyihui ?

**Comment by xiongyihui** [comment]
New version is at https://github.com/respeaker/avs. Still ealy stage. Be the end of this week, a tap-to-talk version is likely to be ready.

**Comment by xiongyihui** [comment]
@jdschuitemaker  just pushed some updates. You can test it right now

**Comment by jdschuitemaker** [comment]
Thank you for the update @xiongyihui .

I am going to check this out. I didn't anticipate such a quick solution, so probably end of week I will look into it.
