### ISSUE TITLE
How to get apt-get on respeaker? 

### ISSUE THREAD

**Issue by sradmard** [respeaker/Alexa#15]
Hi,
It looks like that repeaker is using the lightweight version of package management, opkg, versus the apt-get. However, under the instruction for ubuntu installation of the respeaker/Alexa package, some dependencies are installed using apt-get. I was wondering whether there is any instructions on installing apt-get on respeaker first to be able to install the other dependencies. 
Thanks a lot in advance.

**Comment by xiongyihui** [comment]
Most dependencies are pre-installed on ReSpeaker.
If you don't use the library on Ubuntu, just follow the instructions for ReSpeaker

**Comment by sradmard** [comment]
Thank you for your reply. 
When I try to install "pocketsphinx" on the respeaker under ubuntu through ssh, using the following command, the installation always terminates, and returns "Killed".
$ pip install pocketsphinx
It says in the .pip/pip.log that there was a MemoryError. Is there any way that I can get "pocketsphinx" installed without running into MemoryError?
Also, I tried to install python-dev using the following command in the instruction: 
$ apt-get install python-dev
However, apt-get is not installed on respeaker, and that is why I asked how to install apt-get first. I would appreciate any hints on how to solve these issues.

**Comment by xiongyihui** [comment]
pocketsphinx is already installed on respeaker.

**Comment by sradmard** [comment]
Great, thank you. I was able to make some progress. I was getting some errors associated to poketsphinx when I was trying to change the wakeup name for Alexa implementation. However, those errors where caused by me not paying too much attention to the structure of the keywords.txt and dictionary.txt files. Now that I am over those errors, I am getting Segmentation Fault error when I run the alexa.py code. At the same time all LED lights go RED on respeaker. Is it the same issue as the one on get_started_with_respeaker package: "Getting "Illegal instruction" & "Segmentation fault" errors [#120"](https://github.com/respeaker/get_started_with_respeaker/issues/120)?

**Comment by xiongyihui** [comment]
See https://github.com/respeaker/get_started_with_respeaker/issues/68 to change the keyword.
