### ISSUE TITLE
Invalid syntax issue

### ISSUE THREAD

**Issue by forjeff0406** [respeaker/Alexa#2]
Hi, 

I've successfully sign-in the Amazon account and try to run python alexa.py on respeaker.
But, it shows: SyntaxError: invalid syntax
root@ReSpeaker:/tmp/run/mountd/mmcblk0p1/Alexa# python alexa.py
Traceback (most recent call last):
  File "alexa.py", line 9, in <module>
    from creds import Client_ID, Client_Secret, refresh_token
  File "/tmp/run/mountd/mmcblk0p1/Alexa/creds.py", line 10
    refresh_token = "Atzr|IwEBIJuHUu6whNT40XRWUDtooh1_TvqNq2

What can I do to run Alexa service correctly?

**Comment by xiongyihui** [comment]
Check the file `creds.py`.  Maybe there are multiple `refresh_token` without proper EOL (End Of Line)

**Comment by forjeff0406** [comment]
In this case, how can i get the proper EOL?

**Comment by xiongyihui** [comment]
Check if the last line of `creds.py` is like`Client_Secret = "xzy"refresh_token="yzx"`.

The correct one should be:

```
Client_Secret = "xzy"
refresh_token="yzx"
```
