### ISSUE TITLE
Receiving news or streaming music

### ISSUE THREAD

**Issue by xiongyihui** [respeaker/Alexa#7]
Receiving news or streaming music from the response message's url.

**Comment by cswiger** [comment]
ReSpeaker actually gets the playlist url in the function:

def process_response(self, response):
   if response.status_code == 200:
      for payload in msg.get_payload():
      ...
      if 'directives' in j['messageBody']:
         for directive in j['messageBody']['directives']:
            elif directive['namespace'] == 'AudioPlayer':
               if directive['name'] == 'play':
                  for stream in directive['payload']['audioItem']['streams']:
                     logger.debug('AudioPlayer audio:' + stream['streamUrl'].lstrip('cid:'))

If you just take that logged url, grab the playlist and get the stream, all in ReSpeaker, it'll play the audio!

**Comment by sevencheng798** [comment]
https://github.com/RAKWireless/WisCore
The Link WisCore have supported Amazon Alexa function and can play music stream,e.t - such as you like song, FM iHeartRadio, iTune,Audiabl.

**Comment by xiongyihui** [comment]
New version is at https://github.com/respeaker/avs
